Adding Jitpack publishing configuration.
johnsonandjohnson/Guppy-Android pull request #5
Opened 2019-09-12 19:55 UTC by patrick-dowling

Adding Jitpack publishing configuration.

2019-09-12 19:59 UTC, patrick-dowling commented
Can pull down the library before approving/merging by adding this dependency
implementation 'com.github.johnsonandjohnson:Guppy-Android:feature~publishLibraryUsingJitpack-SNAPSHOT'

2019-09-17 17:54 UTC, CCorrado requested changes
If you can, update the README with instructions on how to add the Guppy project to a project's build.gradle file.

2019-09-18 14:09 UTC, CCorrado commented
Fixes #3

2019-09-18 14:09 UTC, CCorrado approved these changes

2019-09-18 14:10 UTC, merged